const express = require('express')
var bodyParser = require('body-parser')
const app = express()
const { JSDOM } = require( "jsdom" )
const { window } = new JSDOM( "" )
const $ = require( "jquery" )( window )